import DashboardTemplate from "@/components/dashboard";
import MenuList from "../menuList";
export const metadata = {
  title: "Dashboard | Ordering System",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <DashboardTemplate title="Dashboard" id="dashboard" menuList={MenuList}>
      {children}
    </DashboardTemplate>
  );
};
export default RootLayout;
